# Business Understanding

This notebook was split from the original G'Contest final-round working notebook for faster GitHub review. Raw data and data-loading code are intentionally excluded. Saved outputs are preserved so interviewers can inspect the completed analysis and results without rerunning the private dataset.

**Interview focus:** Frames the competition problem, introduces the dataset structure, and records the initial quality checks used before cleaning.

# I. Business Understanding

## Data Context

## Data Loading Removed for Public Review

The original competition dataset was provided during the final round and is not included in this public repository. Data-loading code has been intentionally removed. Saved outputs are preserved throughout the split notebooks so reviewers can inspect the completed analysis workflow.

## Dataset Overview

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25746 entries, 0 to 25745
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   begin_time          25746 non-null  object
 1   close_time          25746 non-null  object
 2   onboarding_status   25746 non-null  object
 3   gender              15012 non-null  object
 4   birth_year          15094 non-null  float64
 5   device_type         20665 non-null  object
 6   device_system_name  20665 non-null  object
 7   os_version          20665 non-null  object
 8   rejected_reason     3067 non-null   object
 9   drop_off_point      25746 non-null  object
 10  cus_id              25746 non-null  int64
dtypes: float64(1), int64(1), object(9)
memory usage: 2.2+ MB

In [4]:
# Count unique customers in the raw dataset.

print(df['cus_id'].nunique())

9148

In [5]:
# Inspect the observation window covered by begin_time.

print("Min begin_time:", df.begin_time.min())
print("Max begin_time:", df.begin_time.max())

Min begin_time: 01/02/2024 05:39
Max begin_time: 31/03/2024 21:05

In [6]:
df.describe(include = 'all')

,begin_time,close_time,onboarding_status,gender,birth_year,device_type,device_system_name,os_version,rejected_reason,drop_off_point,cus_id
count,25746,25746,25746,15012,15094.000000,20665,20665,20665,3067,25746,25746.000000
unique,10558,10198,3,2,NaN,24,3,95,12,7,NaN
top,29/02/2024 13:48,29/02/2024 13:47,PENDING,F,NaN,Apple,iOS,17.3.1,document-ocr-failed,account-creation,NaN
freq,172,171,11281,8481,NaN,16036,16014,5491,2622,8543,NaN
mean,NaN,NaN,NaN,NaN,1990.220419,NaN,NaN,NaN,NaN,NaN,4554.582537
std,NaN,NaN,NaN,NaN,9.700667,NaN,NaN,NaN,NaN,NaN,2632.626100
min,NaN,NaN,NaN,NaN,1199.000000,NaN,NaN,NaN,NaN,NaN,0.000000
25%,NaN,NaN,NaN,NaN,1986.000000,NaN,NaN,NaN,NaN,NaN,2315.250000
50%,NaN,NaN,NaN,NaN,1992.000000,NaN,NaN,NaN,NaN,NaN,4526.000000
75%,NaN,NaN,NaN,NaN,1995.000000,NaN,NaN,NaN,NaN,NaN,6822.750000
max,NaN,NaN,NaN,NaN,2003.000000,NaN,NaN,NaN,NaN,NaN,9147.000000

In [7]:
df.head(20)

,begin_time,close_time,onboarding_status,gender,birth_year,device_type,device_system_name,os_version,rejected_reason,drop_off_point,cus_id
0,02/02/2024 16:52,02/02/2024 17:55,SUCCESSFUL,F,1985.0,Apple,iOS,16.7.2,NaN,account-creation,2578
1,02/02/2024 16:33,02/02/2024 16:35,SUCCESSFUL,M,1990.0,Apple,iOS,16.1,NaN,account-creation,5181
2,02/02/2024 14:47,02/02/2024 16:55,SUCCESSFUL,F,2000.0,Apple,iOS,17.2.1,NaN,account-creation,816
3,02/02/2024 16:40,02/02/2024 16:48,SUCCESSFUL,M,1980.0,samsung,Android,12,NaN,account-creation,3562
4,02/02/2024 14:53,03/02/2024 15:24,SUCCESSFUL,F,1988.0,Apple,iOS,17.1.2,NaN,account-creation,4672
5,28/02/2024 15:29,28/02/2024 15:32,SUCCESSFUL,M,1997.0,Apple,iOS,17.3.1,NaN,account-creation,3255
6,28/02/2024 15:23,28/02/2024 15:27,SUCCESSFUL,F,1978.0,samsung,Android,12,NaN,account-creation,2800
7,28/02/2024 15:21,28/02/2024 15:24,SUCCESSFUL,M,1989.0,samsung,Android,14,NaN,account-creation,4195
8,29/02/2024 13:38,29/02/2024 13:42,SUCCESSFUL,F,1992.0,Apple,iOS,17.3.1,NaN,account-creation,331
9,29/02/2024 13:32,29/02/2024 13:34,SUCCESSFUL,F,1999.0,Apple,iOS,17.3.1,NaN,account-creation,1585
10,29/02/2024 13:25,29/02/2024 13:28,SUCCESSFUL,F,1996.0,Apple,iOS,17.1.2,NaN,account-creation,6849
11,28/02/2024 15:59,28/02/2024 16:02,SUCCESSFUL,M,1992.0,KDDI,Android,10,NaN,account-creation,8652
12,02/02/2024 16:51,02/02/2024 16:54,SUCCESSFUL,F,1993.0,Apple,iOS,16.6,NaN,account-creation,949
13,29/02/2024 14:18,29/02/2024 14:19,SUCCESSFUL,M,1995.0,Apple,iOS,16.6.1,NaN,account-creation,5708
14,15/02/2024 11:04,15/02/2024 11:07,SUCCESSFUL,F,1992.0,Apple,iOS,17.2.1,NaN,account-creation,1566
15,18/02/2024 20:56,18/02/2024 20:59,SUCCESSFUL,F,1999.0,Apple,iOS,16.6,NaN,account-creation,8074
16,29/02/2024 14:47,29/02/2024 14:50,SUCCESSFUL,F,1997.0,Apple,iOS,17.2.1,NaN,account-creation,1001
17,29/02/2024 14:46,29/02/2024 18:48,SUCCESSFUL,M,1971.0,samsung,Android,13,NaN,account-creation,2848
18,29/02/2024 07:47,29/02/2024 07:49,SUCCESSFUL,M,1996.0,samsung,Android,12,NaN,account-creation,7386
19,29/02/2024 11:35,29/02/2024 11:38,SUCCESSFUL,F,1998.0,Apple,iOS,16.3.1,NaN,account-creation,516

In [8]:
df.isna().sum()

begin_time                0
close_time                0
onboarding_status         0
gender                10734
birth_year            10652
device_type            5081
device_system_name     5081
os_version             5081
rejected_reason       22679
drop_off_point            0
cus_id                    0
dtype: int64

In [9]:
df.isna().mean() * 100

begin_time             0.000000
close_time             0.000000
onboarding_status      0.000000
gender                41.691913
birth_year            41.373417
device_type           19.735104
device_system_name    19.735104
os_version            19.735104
rejected_reason       88.087470
drop_off_point         0.000000
cus_id                 0.000000
dtype: float64